version: "3.8"

services:
  nova_nexus:
    build: .
    container_name: nova_nexus_app
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8550:8550"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - FLET_WEB_MODE=1
    volumes:
      - nova_data:/app/backend/data

volumes:
  nova_data:
